#!/usr/bin/env python3
"""
Triplet of Pairs — Bayesian Calculator — WQC Spring 2026
==========================================================
Bayesian inference on hidden d5 die faces from observed rolls.
Cross-contract inference from market prices.

Events A, B, C each generated by:
  1) Draw 5 faces from {1,...,10} with replacement → forms a d5
  2) Roll that d5 nine times, sum the results

Contracts: AB = A+B,  BC = B+C,  AC = A+C
You observe only ONE event's rolls.

E[each event] = 49.5 (prior)
E[each pair contract] = 99 (prior)
"""

import math
from itertools import combinations_with_replacement


# ─── Enumerate all possible dice ────────────────────────────────

def enumerate_all_freq_vectors():
    """
    Enumerate all frequency vectors (n1,...,n10) where Σni = 5.
    n_i = number of faces equal to i.
    Returns list of tuples of length 10.
    """
    vectors = []

    def _recurse(remaining, min_idx, current):
        if min_idx == 9:  # last index, fill remainder
            vectors.append(tuple(current + [remaining]))
            return
        for count in range(remaining + 1):
            _recurse(remaining - count, min_idx + 1, current + [count])

    _recurse(5, 0, [])
    return vectors


def multinomial_coefficient(freq):
    """5! / (n1! * n2! * ... * n10!)"""
    n = sum(freq)
    result = math.factorial(n)
    for f in freq:
        result //= math.factorial(f)
    return result


def compute_prior(freq):
    """Prior probability: multinomial(5; 1/10,...,1/10) = C(5;freq) * (1/10)^5"""
    return multinomial_coefficient(freq) * (0.1 ** 5)


# ─── Calculator ──────────────────────────────────────────────────

class TripletCalculator:
    def __init__(self):
        # Enumerate all possible d5 dice
        self.all_freqs = enumerate_all_freq_vectors()
        self.num_dice = len(self.all_freqs)

        # Compute priors
        priors = [compute_prior(f) for f in self.all_freqs]
        total = sum(priors)
        self.posteriors = [p / total for p in priors]

        # State
        self.my_event = None   # 'A', 'B', or 'C'
        self.my_rolls = []     # observed rolls (1-10)

        # Market prices for cross-inference
        self.market_ab = 99.0
        self.market_bc = 99.0
        self.market_ac = 99.0

    def set_event(self, event):
        self.my_event = event.upper()

    def add_roll(self, value):
        if not (1 <= value <= 10):
            return False
        if len(self.my_rolls) >= 9:
            return False
        self.my_rolls.append(value)
        self._bayesian_update(value)
        return True

    def undo_roll(self):
        if not self.my_rolls:
            return False
        self.my_rolls.pop()
        self._rebuild_posterior()
        return True

    def _bayesian_update(self, observed_value):
        """Update posterior: P(die | data) ∝ P(observed | die) * P(die | prev data)"""
        idx = observed_value - 1  # 0-indexed into freq vector
        new_post = []
        for i, freq in enumerate(self.all_freqs):
            # Likelihood: P(rolling observed_value | this die) = freq[idx] / 5
            likelihood = freq[idx] / 5.0
            new_post.append(self.posteriors[i] * likelihood)

        total = sum(new_post)
        if total > 0:
            self.posteriors = [p / total for p in new_post]

    def _rebuild_posterior(self):
        """Rebuild posterior from scratch using all current rolls."""
        priors = [compute_prior(f) for f in self.all_freqs]
        total = sum(priors)
        self.posteriors = [p / total for p in priors]
        for r in self.my_rolls:
            self._bayesian_update(r)

    # ── Expected values ──────────────────────────────────────────

    def expected_next_roll(self):
        """E[next roll] = Σ_die P(die) * E[roll | die]"""
        e = 0.0
        for i, freq in enumerate(self.all_freqs):
            # E[roll | die] = Σ v * freq[v-1] / 5
            e_given_die = sum(v * freq[v - 1] / 5.0 for v in range(1, 11))
            e += self.posteriors[i] * e_given_die
        return e

    def var_next_roll(self):
        """Var[next roll] accounting for die uncertainty."""
        e1 = 0.0  # E[roll]
        e2 = 0.0  # E[roll^2]
        for i, freq in enumerate(self.all_freqs):
            e1_die = sum(v * freq[v - 1] / 5.0 for v in range(1, 11))
            e2_die = sum(v ** 2 * freq[v - 1] / 5.0 for v in range(1, 11))
            e1 += self.posteriors[i] * e1_die
            e2 += self.posteriors[i] * e2_die
        return e2 - e1 ** 2

    def expected_event_total(self):
        """E[my event] = sum_observed + remaining * E[next roll]"""
        observed = sum(self.my_rolls)
        remaining = 9 - len(self.my_rolls)
        return observed + remaining * self.expected_next_roll()

    def std_event_remaining(self):
        """Approximate std dev of the remaining sum."""
        remaining = 9 - len(self.my_rolls)
        if remaining == 0:
            return 0.0
        v = self.var_next_roll()
        return math.sqrt(remaining * v) if v > 0 else 0.0

    # ── Cross-contract inference ─────────────────────────────────

    def infer_other_events(self):
        """
        Use market prices + your event estimate to infer the other two events.
        AB = A+B, BC = B+C, AC = A+C
        """
        my_est = self.expected_event_total()
        est = {}

        if self.my_event == 'A':
            est['A'] = my_est
            est['B'] = self.market_ab - my_est
            est['C'] = self.market_ac - my_est
        elif self.my_event == 'B':
            est['A'] = self.market_ab - my_est
            est['B'] = my_est
            est['C'] = self.market_bc - my_est
        elif self.my_event == 'C':
            est['A'] = self.market_ac - my_est
            est['B'] = self.market_bc - my_est
            est['C'] = my_est
        else:
            est = {'A': 49.5, 'B': 49.5, 'C': 49.5}

        return est

    def fair_contracts(self):
        est = self.infer_other_events()
        return {
            'AB': est['A'] + est['B'],
            'BC': est['B'] + est['C'],
            'AC': est['A'] + est['C'],
        }

    # ── Face distribution analysis ───────────────────────────────

    def face_probabilities(self):
        """P(next roll = v) for v in 1..10"""
        probs = [0.0] * 10
        for i, freq in enumerate(self.all_freqs):
            for v in range(10):
                probs[v] += self.posteriors[i] * freq[v] / 5.0
        return probs

    def top_dice(self, n=5):
        """Top N most likely dice (as face lists) with probabilities."""
        indexed = []
        for i, freq in enumerate(self.all_freqs):
            # Convert freq vector back to face list
            faces = []
            for v in range(10):
                faces.extend([v + 1] * freq[v])
            indexed.append((self.posteriors[i], faces))
        indexed.sort(key=lambda x: -x[0])
        return indexed[:n]

    def entropy(self):
        """Shannon entropy of posterior (bits). Lower = more certain."""
        h = 0.0
        for p in self.posteriors:
            if p > 0:
                h -= p * math.log2(p)
        return h

    # ── Display ──────────────────────────────────────────────────

    def display(self):
        remaining = 9 - len(self.my_rolls)
        observed_sum = sum(self.my_rolls)

        print("\n" + "=" * 62)
        print("  Triplet of Pairs — Bayesian Calculator")
        print("=" * 62)

        print(f"  Your event: {self.my_event or '(not set — use: event A/B/C)'}")
        rolls_str = ', '.join(str(r) for r in self.my_rolls) if self.my_rolls else '—'
        print(f"  Rolls ({len(self.my_rolls)}/9): {rolls_str}")
        print(f"  Sum so far: {observed_sum}    Remaining: {remaining}")

        # ── Bayesian inference ────────────────────────────────────
        e_next = self.expected_next_roll()
        e_total = self.expected_event_total()
        sd = self.std_event_remaining()
        ent = self.entropy()

        print(f"\n  ── Die Inference ──")
        print(f"  E[next roll]:     {e_next:.3f}")
        print(f"  E[event total]:   {e_total:.2f}  ({observed_sum} + {remaining}×{e_next:.2f})")
        print(f"  ±1σ range:        [{e_total - sd:.1f}, {e_total + sd:.1f}]")
        print(f"  Posterior entropy: {ent:.2f} bits  (lower = more certain)")

        # Face probability distribution
        face_probs = self.face_probabilities()
        print(f"\n  P(next roll = v):")
        print(f"    v:  ", end="")
        for v in range(1, 11):
            print(f" {v:>5}", end="")
        print()
        print(f"    P:  ", end="")
        for v in range(10):
            print(f" {face_probs[v]:>5.1%}", end="")
        print()

        # Top dice
        print(f"\n  Top 5 most likely dice:")
        for prob, faces in self.top_dice(5):
            if prob < 0.001:
                break
            faces_str = str(faces)
            e_die = sum(faces) / 5.0
            print(f"    {faces_str:<22} P={prob*100:>5.1f}%  E[roll]={e_die:.1f}")

        # ── Cross-contract inference ─────────────────────────────
        if self.my_event:
            est = self.infer_other_events()
            fc = self.fair_contracts()

            print(f"\n  ── Market Inference ──")
            print(f"  Market:  AB={self.market_ab:.1f}   BC={self.market_bc:.1f}   AC={self.market_ac:.1f}")
            print(f"  Inferred events:")
            for ev in ['A', 'B', 'C']:
                marker = " ◄ yours" if ev == self.my_event else ""
                print(f"    E[{ev}] = {est[ev]:.2f}{marker}")

            print(f"\n  ── Fair Contract Prices ──")
            print(f"    AB = {fc['AB']:.2f}    (market {self.market_ab:.1f}  Δ={fc['AB']-self.market_ab:+.2f})")
            print(f"    BC = {fc['BC']:.2f}    (market {self.market_bc:.1f}  Δ={fc['BC']-self.market_bc:+.2f})")
            print(f"    AC = {fc['AC']:.2f}    (market {self.market_ac:.1f}  Δ={fc['AC']-self.market_ac:+.2f})")

            # Consistency check
            s = fc['AB'] + fc['BC'] + fc['AC']
            print(f"\n  Consistency: AB+BC+AC = {s:.2f}  ≈ 2(A+B+C) = {2*sum(est.values()):.2f}")

            # Trading signals
            print(f"\n  ── Trading Signals ──")
            for contract, key in [('AB', 'AB'), ('BC', 'BC'), ('AC', 'AC')]:
                delta = fc[key] - getattr(self, f'market_{key.lower()}')
                if abs(delta) > 2:
                    direction = "BUY" if delta > 0 else "SELL"
                    print(f"    {direction} {contract} (fair={fc[key]:.1f} vs market={getattr(self, f'market_{key.lower()}'):.1f}, edge={abs(delta):.1f})")
                else:
                    print(f"    {contract}: no strong signal (edge={abs(delta):.1f})")

        print("=" * 62)


def print_help():
    print("""
  Commands:
  ─────────────────────────────────────────────────
  event A         Set your assigned event (A, B, or C)
  roll 7          Add observed roll value (1-10)
  undo            Remove last roll

  ab 102          Set market price for AB contract
  bc 95           Set market price for BC contract
  ac 100          Set market price for AC contract
  mp 102 95 100   Set all market prices at once (AB BC AC)

  reset           Clear rolls and reset posterior
  full            Full reset including event assignment
  help            Show this help
  q               Quit
  ─────────────────────────────────────────────────
  Typical workflow:
    1) Set your event assignment: event A
    2) As rolls come in, enter: roll 6
    3) Update market prices: ab 103  (or mp 103 95 100)
    4) Read the trading signals
""")


def main():
    calc = TripletCalculator()

    print("╔══════════════════════════════════════════════╗")
    print("║   Triplet of Pairs — Bayesian Calculator     ║")
    print("║   WQC Spring 2026                            ║")
    print("╚══════════════════════════════════════════════╝")
    print(f"  Enumerated {calc.num_dice} possible dice.")
    print_help()
    calc.display()

    while True:
        try:
            raw = input("\n> ").strip()
            if not raw:
                continue
            parts = raw.split()
            cmd = parts[0].lower()

            if cmd in ('q', 'quit', 'exit'):
                print("  Goodbye!")
                break

            elif cmd == 'help':
                print_help()
                continue

            elif cmd == 'reset':
                ev = calc.my_event
                mab, mbc, mac = calc.market_ab, calc.market_bc, calc.market_ac
                calc.__init__()
                calc.my_event = ev
                calc.market_ab, calc.market_bc, calc.market_ac = mab, mbc, mac
                print("  Rolls cleared, posterior reset. Event and market prices kept.")
                calc.display()

            elif cmd == 'full':
                calc.__init__()
                print("  Full reset.")
                calc.display()

            elif cmd == 'event' and len(parts) == 2:
                ev = parts[1].upper()
                if ev in ('A', 'B', 'C'):
                    calc.set_event(ev)
                    print(f"  Assigned to event {ev}")
                    calc.display()
                else:
                    print("  Must be A, B, or C")

            elif cmd == 'roll' and len(parts) == 2:
                val = int(parts[1])
                if calc.add_roll(val):
                    print(f"  Added roll: {val}")
                    calc.display()
                else:
                    print("  Invalid (must be 1-10, max 9 rolls)")

            elif cmd == 'undo':
                if calc.undo_roll():
                    print("  Removed last roll")
                    calc.display()
                else:
                    print("  Nothing to undo")

            elif cmd == 'ab' and len(parts) == 2:
                calc.market_ab = float(parts[1])
                calc.display()

            elif cmd == 'bc' and len(parts) == 2:
                calc.market_bc = float(parts[1])
                calc.display()

            elif cmd == 'ac' and len(parts) == 2:
                calc.market_ac = float(parts[1])
                calc.display()

            elif cmd == 'mp' and len(parts) == 4:
                calc.market_ab = float(parts[1])
                calc.market_bc = float(parts[2])
                calc.market_ac = float(parts[3])
                print(f"  Market prices set: AB={calc.market_ab} BC={calc.market_bc} AC={calc.market_ac}")
                calc.display()

            else:
                print("  Unknown command. Type 'help' for usage.")

        except ValueError:
            print("  Invalid number. Try again.")
        except (EOFError, KeyboardInterrupt):
            print("\n  Goodbye!")
            break


if __name__ == '__main__':
    main()
